# Generated by Django 5.1.12 on 2025-09-17 08:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywifipass', '0006_alter_wifinetworklocation_ssid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycustomcert',
            options={'verbose_name': 'certificate', 'verbose_name_plural': 'certificates'},
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='requires_validator',
            field=models.BooleanField(default=True, help_text='If True, users need to be validated by an admin before accessing certificates'),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='send_emails_automatically',
            field=models.BooleanField(default=True, help_text='If True, emails are sent automatically when users register or are updated'),
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if registration email has been sent to the user'),
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when the last email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2035, 9, 17), null=True),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='wifiLocation',
            field=models.ForeignKey(db_column='location_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mywifipass.wifinetworklocation'),
        ),
        migrations.AlterUniqueTogether(
            name='mycustomcert',
            unique_together={('ca', 'serial_number')},
        ),
    ]
