# Copyright (c) 2025, Pablo Diz de la Cruz
# All rights reserved.
# Licensed under the BSD 3-Clause License. See LICENSE file in the project root for full license information.

services:
  mywifipass:
    build:
      context: . # Because i need to copy this whole directory inside
      dockerfile: Dockerfile_mywifipass
    container_name: mywifipass
    volumes:
      - shared-certs:/djangox509/mywifipass/server_certs
      - webapp_secrets:/djangox509/mywifipass/secrets
      - logos:/djangox509/mywifipass/logos
    ports:
      - "${WEBAPP_PORT}:8000"
    working_dir: /djangox509/mywifipass
    networks:
      - mywifipass_network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database # Name of the Container, do not change 
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DEBUG
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_HOST
      - EMAIL_USE_TLS
      - EMAIL_HOST_PORT
      - DOMAIN
      - SSL 
      - TIME_ZONE
  radius:
    build: ./our_radius
    container_name: radius-server
    ports:
      - "${RADIUS_PORT}:1812/udp"
    environment:
      - RADIUS_CLIENT_IP
    volumes:
      - shared-certs:/etc/raddb/server_certs
      - radius_config:/etc/raddb
      - ./our_radius/RADIUS_SECRET:/etc/raddb/secret/
    networks:
      - mywifipass_network
    restart: always
  database:
      image: postgres:15
      container_name: database
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
      volumes:
        - database_data:/var/lib/postgresql/data
      networks:
        - mywifipass_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
        interval: 5s
        timeout: 5s
        retries: 3
volumes:
  shared-certs:  # Shared volume for certificates
  database_data:  # Volume for database
  radius_config: # Volume for RADIUS server configuration
  webapp_secrets: # Volume for Django secrets
  logos: # Volume for event logos

networks:
  mywifipass_network:
    ipam:
      config:
        - subnet: 172.19.0.0/16

