# Copyright (c) 2025, Pablo Diz de la Cruz
# All rights reserved.
# Licensed under the BSD 3-Clause License. See LICENSE file in the project root for full license information.

services:
  radius:  
    build: ./our_radius  
    volumes:
      - radius-openvpn-config:/etc/openvpn  
      - /etc/localtime:/etc/localtime:ro  
    cap_add:
      - NET_ADMIN  
    devices:
      - /dev/net/tun:/dev/net/tun
  
  openvpn:
    container_name: openvpn-server
    volumes: 
      - openvpn-config:/etc/openvpn
    ports:
      - "${OPENVPN_PORT}:1194/udp"  

  freeradius:
    deploy: 
      replicas: 0

  dashboard:
    image: openwisp/openwisp-dashboard:24.11.2
    container_name: openwisp-dashboard

  celery:
    image: openwisp/openwisp-dashboard:24.11.2

  celery_monitoring:
    image: openwisp/openwisp-dashboard:24.11.2
  
  celerybeat:
    image: openwisp/openwisp-dashboard:24.11.2
  
  postgres:
    container_name: openwisp-postgres

volumes:
  radius-openvpn-config:  
  openvpn-config: 

# docker compose down && docker volume prune && docker compose -f docker-compose.yaml  -f docker-compose.override.yaml up  -d