services:
  djangox509:
    build:
      context: . # Because i need to copy this whole directory inside
      dockerfile: Dockerfile_getEAP_TLS 
    container_name: webapp
    volumes:
      - shared-certs:/djangox509/getEAP_TLS/server_certs
      - webapp_secrets:/djangox509/getEAP_TLS/secrets
      - logos:/djangox509/getEAP_TLS/logos
    ports:
      - "${WEBAPP_PORT}:8000"
    working_dir: /djangox509/getEAP_TLS
    networks:
      - our_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_SERVER=mysql-server # Name of the Container, do not change 
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DEBUG
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_HOST
      - EMAIL_USE_TLS
      - EMAIL_HOST_PORT
      - DOMAIN
      - SSL 
      - TIME_ZONE
  radius:
    build: ./our_radius
    container_name: radius-server
    ports:
      - "${RADIUS_PORT}:1812/udp"
    environment:
      - RADIUS_CLIENT_IP
      - RADIUS_SECRET
    volumes:
      - shared-certs:/etc/raddb/server_certs
      - radius_config:/etc/raddb
    networks:
      - our_network
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - our_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  shared-certs:  # Shared volume for certificates
  mysql_data:  # Volume for MySQL
  radius_config: # Volume for RADIUS server configuration
  webapp_secrets: # Volume for Django secrets
  logos: # Volume for events logos

networks:
  our_network:
    driver: bridge
