FROM python:latest


ENV DIR="/djangox509"
RUN mkdir $DIR
WORKDIR $DIR
COPY .. $DIR

RUN pip3 install -U pip setuptools wheel
RUN pip3 install -e .
RUN pip3 install -r mywifipass/requirements.txt

WORKDIR $DIR/mywifipass
EXPOSE 8000
ENV NAME djangox509

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

ENTRYPOINT ./docker-entrypoint.sh && \ 
    gunicorn --bind 0.0.0.0:8000 --workers=3 mywifipass.wsgi:application
    #With SSL
    #gunicorn --bind 0.0.0.0:8000 --workers=3 --certfile=cert.pem --keyfile=key.pem mywifipass.wsgi:application