# Generated by Django 5.1.7 on 2025-03-23 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0001_initial'),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wifiuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wifiuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='certificate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_X509_CERT_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='id_document',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
