# Generated by Django 5.1.9 on 2025-05-19 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0002_logintoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifiuser',
            old_name='allow_access',
            new_name='has_attended',
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='form_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='is_enabled_in_radius',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='is_registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='is_visible_in_web',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='SSID',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2035, 5, 19), null=True),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='name',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
