# Generated by Django 5.1.7 on 2025-03-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0003_wifinetworklocation_delete_wifilocation'),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='wifiLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='getEAP_TLS.wifinetworklocation'),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.DJANGO_X509_CERT_MODEL),
        ),
    ]
