# Generated by Django 5.1.9 on 2025-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0003_rename_allow_access_wifiuser_has_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='has_downloaded_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='SSID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
