# Generated by Django 5.1.7 on 2025-03-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0004_wifiuser_wifilocation_alter_wifiuser_certificate'),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wifinetworklocation',
            name='ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.DJANGO_X509_CERT_MODEL),
        ),
    ]
