# Generated by Django 5.1.7 on 2025-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0006_alter_wifinetworklocation_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifinetworklocation',
            name='SSID',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
