# Generated by Django 5.1.7 on 2025-03-23 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0007_wifinetworklocation_ssid'),
        migrations.swappable_dependency(settings.DJANGO_X509_CA_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifinetworklocation',
            name='ca',
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='certificates_CA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_CA', to=settings.DJANGO_X509_CA_MODEL),
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='radius_CA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_CA', to=settings.DJANGO_X509_CA_MODEL),
        ),
    ]
