# Generated by Django 5.1.7 on 2025-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0008_remove_wifinetworklocation_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
