# Generated by Django 5.1.7 on 2025-03-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0009_wifiuser_uuid'),
        migrations.swappable_dependency(settings.DJANGO_X509_CA_MODEL),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifiuser',
            old_name='uuid',
            new_name='user_uuid',
        ),
        migrations.RemoveField(
            model_name='wifinetworklocation',
            name='radius_CA',
        ),
        migrations.AddField(
            model_name='wifinetworklocation',
            name='radius_Certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.DJANGO_X509_CERT_MODEL),
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='email',
            field=models.EmailField(default='example.com', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='SSID',
            field=models.CharField(default='SSID', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='certificates_CA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.DJANGO_X509_CA_MODEL),
        ),
    ]
