# Generated by Django 5.1.8 on 2025-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0010_rename_uuid_wifiuser_user_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='symmetric_key',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
    ]
