# Generated by Django 5.1.8 on 2025-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0011_wifiuser_symmetric_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifiuser',
            old_name='symmetric_key',
            new_name='certificates_symmetric_key',
        ),
    ]
