# Generated by Django 5.1.8 on 2025-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0012_rename_symmetric_key_wifiuser_certificates_symmetric_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='allow_access',
            field=models.BooleanField(default=False),
        ),
    ]
