# Generated by Django 5.1.8 on 2025-05-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getEAP_TLS', '0015_mycustomcert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycustomcert',
            options={'verbose_name': 'CA', 'verbose_name_plural': 'CAs'},
        ),
        migrations.AlterUniqueTogether(
            name='mycustomcert',
            unique_together=set(),
        ),
    ]
