# Generated by Django 5.1.15 on 2026-03-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mywifipass', '0012_remove_wifiuser_wifilocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(help_text='Base64-encoded FIDO2 credential ID (public, non-secret)', max_length=500, unique=True)),
                ('public_key', models.TextField(help_text='JSON serialized JWK (Joint Web Key) public key for verification')),
                ('sign_count', models.IntegerField(default=0, help_text='Signature counter for replay attack detection')),
                ('attestation_format', models.CharField(default='none', help_text='FIDO2 attestation format (none, self, fido-u2f, packed, etc.)', max_length=50)),
                ('algorithm', models.IntegerField(default=-7, help_text='COSE algorithm identifier (ES256 = -7, more at https://www.iana.org/assignments/cose/cose.xhtml)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the passkey was registered')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last successful authentication timestamp', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential is currently usable for authentication')),
                ('wifi_user', models.OneToOneField(help_text='Reference to the WiFi user who owns this passkey', on_delete=django.db.models.deletion.CASCADE, related_name='passkey_credential', to='mywifipass.wifiuser')),
            ],
            options={
                'verbose_name': 'Passkey Credential',
                'verbose_name_plural': 'Passkey Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
