# Generated by Django 5.1.15 on 2026-03-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fido2_poc', '0001_initial'),
        ('mywifipass', '0012_remove_wifiuser_wifilocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fido2NetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_fido2', models.BooleanField(default=False, help_text='If True, users must validate their passes using a FIDO2 passkey via the app.')),
                ('network', models.OneToOneField(help_text='The network this FIDO2 configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='fido2_config', to='mywifipass.wifinetworklocation')),
            ],
            options={
                'verbose_name': 'FIDO2 Network Config',
                'verbose_name_plural': 'FIDO2 Network Configs',
            },
        ),
    ]
