# Copyright (c) 2025, Pablo Diz de la Cruz
# All rights reserved.
# Licensed under the BSD 3-Clause License. See LICENSE file in the project root for full license information.

# AuthenticationChallenge was never tracked by Django migrations (table existed
# via syncdb). SeparateDatabaseAndState is used to:
#   - Register the model in the Django state (state_operations)
#   - Apply only the schema deltas to the existing table (database_operations)
#
# Schema changes applied to the database:
#   1. email: DROP NOT NULL  (nullable for discoverable-mode challenges)
#   2. session_id: ADD COLUMN uuid UNIQUE  (challenge key for discoverable mode)
#
# Apply with: python manage.py migrate fido2_poc

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fido2_poc', '0002_fido2networkconfig'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(

            # --- State only ---
            # Register AuthenticationChallenge in Django's migration graph so
            # future migrations can reference it normally.
            state_operations=[
                migrations.CreateModel(
                    name='AuthenticationChallenge',
                    fields=[
                        ('id', models.BigAutoField(
                            auto_created=True, primary_key=True,
                            serialize=False, verbose_name='ID',
                        )),
                        ('email', models.EmailField(
                            blank=True, null=True, default=None,
                            help_text=(
                                'User email for the legacy email-based flow. '
                                'Null when using the discoverable (session_id) flow.'
                            ),
                        )),
                        ('session_id', models.UUIDField(
                            blank=True, null=True, unique=True,
                            db_index=True, default=None,
                            help_text=(
                                'Random UUID generated by /authenticate/start/ for the '
                                'discoverable flow. Null when using the email-based flow.'
                            ),
                        )),
                        ('challenge', models.TextField(
                            help_text='Base64-encoded WebAuthn challenge (non-secret, unique per request)',
                        )),
                        ('created_at', models.DateTimeField(
                            auto_now_add=True,
                            help_text='Challenge creation timestamp',
                        )),
                    ],
                    options={
                        'verbose_name': 'Authentication Challenge',
                        'verbose_name_plural': 'Authentication Challenges',
                        'ordering': ['-created_at'],
                    },
                ),
            ],

            # --- Database only ---
            # The table already exists. Only apply the two schema changes needed
            # for discoverable mode; do NOT recreate the table.
            database_operations=[

                # 1. Make email nullable so discoverable challenges can omit it.
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE fido2_poc_authenticationchallenge '
                        'ALTER COLUMN email DROP NOT NULL'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # 2. Add session_id column.
                #    PostgreSQL UNIQUE on a nullable column allows multiple NULLs,
                #    so no partial index trick is needed.
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE fido2_poc_authenticationchallenge '
                        'ADD COLUMN IF NOT EXISTS session_id uuid DEFAULT NULL UNIQUE'
                    ),
                    reverse_sql=(
                        'ALTER TABLE fido2_poc_authenticationchallenge '
                        'DROP COLUMN IF EXISTS session_id'
                    ),
                ),
            ],
        ),
    ]
