# Generated by Django 5.1.9 on 2025-05-26 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywifipass', '0004_wifiuser_has_downloaded_pass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wifinetworklocation',
            options={'ordering': ['name'], 'verbose_name': 'Wifi Network', 'verbose_name_plural': 'Wifi Networks'},
        ),
        migrations.AlterModelOptions(
            name='wifiuser',
            options={'ordering': ['name'], 'verbose_name': 'Wifi Client', 'verbose_name_plural': 'Wifi Clients'},
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2035, 5, 27), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wifiuser',
            unique_together={('user_uuid', 'wifiLocation')},
        ),
    ]
