# Generated by Django 5.1.13 on 2025-10-21 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywifipass', '0007_alter_mycustomcert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='android_version',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2035, 10, 21), null=True),
        ),
    ]
