# Generated by Django 5.1.13 on 2026-03-23 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywifipass', '0008_alter_wifiuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifinetworklocation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2036, 3, 22), null=True),
        ),
    ]
