# Generated by Django 5.1.15 on 2026-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywifipass', '0013_alter_wifinetworklocation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiuser',
            name='id_document',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
